import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Calculadora Sintactica',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <title> Calculadora Sintactica</title>
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
